config/routes.rb
Rails.application.routes.draw do
  root "users#home"
  get "home/about" => "users#about"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships,  only: [:create, :destroy]
  end
  get "searches" => "searches#index"
  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  attachment :profile_image
  validates :name, length: { minimum: 2 }
  validates :name, length: {maximum: 20 }
  validates :name, presence: true
  validates :introduction, length: {  maximum: 50 }

    # ユーザーをフォローする
    def follow(other_user)
      following << other_user
    end
  
    # ユーザーをフォロー解除する
    def unfollow(other_user)
      active_relationships.find_by(followed_id: other_user.id).destroy
    end
  
    # 現在のユーザーがフォローしてたらtrueを返す
    def following?(other_user)
      following.include?(other_user)
    end

      def self.search(search,word)
        if search == "forward_match"
                        @users = User.where("name LIKE ?","#{word}%")
        elsif search == "backward_match"
                        @users = User.where("name LIKE ?","%#{word}")
        elsif search == "perfect_match"
                        @users = User.where(name: word)
        elsif search == "partial_match"
                        @users = User.where("name LIKE ?","%#{word}%")
        else
          @users = User.all
        end
      end

  include JpPrefecture
  jp_prefecture :prefecture_code
  
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end
  
  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home 
  end
  def about
  end

  def show
    @user = User.find(params[:id])
    @books = Book.where(user_id: @user.id)
    @book = Book.new
  end

  def index
    @users = User.all
    @user = current_user
    @book = Book.new
  end
  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
      redirect_to user_path(current_user.id)
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end
  def following
    @user  = User.find(params[:id])
    @users = @user.following
  end

  def followers
    @user  = User.find(params[:id])
    @users = @user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name,:profile_image,:introduction)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
  <div class="row">
    <%= link_to edit_user_path(current_user.id) do %>
      <i class="col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_16420"></i>
    <% end %>
  </div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, url:user_relationships_path(user)) do |f| %>
  <div><%= hidden_field_tag :followed_id, user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == user %>
  <div id="follow_form">
  <% if current_user.following?(user) %>
    <%= render 'unfollow', user:@user %>
  <% else %>
    <%= render 'follow', user:@user %>
  <% end %>
  </div>
<% end %>

app/views/users/_new.html.erb
  <h2>User info</h2>
  <%= attachment_image_tag user, :profile_image ,class:"attachment user profile_image fallback" ,format: 'jpeg', fallback:"no_image.jpg",size: "100x100"%>
  <table class="table">
    <tbody>
      <tr></tr> 
      <tr>
    	  <th>name</th>
    	  <th><%= user.name %></th>
      </tr>
      <tr>
    	  <th>introduction</th>
    	  <th><%= user.introduction %></th>
      </tr>
      <tr>
        <th>follows</th>
        <Th><%= link_to  user.following.count , following_user_path(user) %></th>
      </tr>
      <tr>
        <th>followers</th>
        <th><%= link_to user.followers.count , followers_user_path(user) %></th>
      </tr>
    </tbody>
  </table>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: user.id), url:user_relationships_path(user),
             html: { method: :delete }) do |f| %>
  <%= f.submit "フォローを外す", class: "btn" %>
<% end %>

app/views/users/about.html.erb
<div class="container">
  <p id="notice"></p>
  <h1>Welcome to <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>!</h1>
</div>

app/views/users/edit.html.erb
<div class="body">
  <div class="container">

    <h2>User info</h2>
        <% if @user.errors.any? %>
      <div id="error_explanation">
        <h2><%= @user.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= form_for(@user, url: user_path) do |f| %>
      <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name, class:"name" %>
      </div>
      
      <div class="field">
        <%= f.label :profile_image , "Image" %>
        <%= f.attachment_field :profile_image %>
      </div>
      
      <div class="field">
        <%= f.label :introduction %>
        <%= f.text_area :introduction ,class:"introduction" %>
      </div>
      
      <div class="actions">
        <%= f.submit "Update User"%>
      </div>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>followers Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image ,class:"attachment user profile_image", fallback:"no_image.jpg",size: "40x40" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  フォロー数：<%= user.following.count %>
                </td>
                <td>
                  フォロワー数：<%= user.followers.count %>
                </td>
              <% if current_user.following?(user) %>
                <td>
                  <%= link_to "フォローを外す", user_relationships_path(user.id) , method: :delete%>
                </td>
              <% else %>
                <td>
                  <%= link_to "フォローする", user_relationships_path(user.id) , method: :post%>
                </td>
              <% end %>
                <td>
                  <%= link_to "Show" , user_path(user.id) ,class:"user_16454" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/users/following.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <h2>follow Users</h2>
        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
          <tbody>
            <% @users.each do |user| %>
              <tr>
                <td>
                  <%= attachment_image_tag user, :profile_image ,class:"attachment user profile_image", fallback:"no_image.jpg",size: "40x40" %>
                </td>
                <td>
                  <%= user.name %>
                </td>
                <td>
                  フォロー数：<%= user.following.count %>
                </td>
                <td>
                  フォロワー数：<%= user.followers.count %>
                </td>
              <% if current_user.following?(user) %>
                <td>
                  <%= link_to "フォローを外す", user_relationships_path(user.id) , method: :delete%>
                </td>
              <% else %>
                <td>
                  <%= link_to "フォローする", user_relationships_path(user.id) , method: :post%>
                </td>
              <% end %>
                <td>
                  <%= link_to "Show" , user_path(user.id) ,class:"user_16454" %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/users/home.html.erb
<div class="body">
  <div class="container">
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <div class="row">
      <div class="top-message col-md-offset-3 col-md-6">
        <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
        <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
        <p>you can share and exchange  your opinions , inpressions , and emotions</p>
        <p> about various books!</p>
        <div class="btn-wrapper">
          <div class="row">
            <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
          </div>
          <div class="row">
            <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<body>
  <div class="container">
    <div class="row">
      <div class="col-xs-3">
        <%= render 'users/new' , user: @user %>
        <%= render 'users/edit'%>
        <%= render 'books/form' ,book:@book%>
      </div>

      <div class="col-xs-9">
        <h2>Users</h2>

        <table class="table">
          <thead>
            <tr>
              <th>image</th>
              <th>name</th>
              <th colspan="3"></th>
            </tr>
          </thead>
        <tbody>
        <% @users.each do |user| %>
          <tr>
            <td>
              <%= attachment_image_tag user, :profile_image ,class:"attachment user profile_image", fallback:"no_image.jpg",size: "40x40" %>
            </td>
            <td>
              <%= user.name %>
            </td>
            <td>
              フォロー数：<%= user.following.count%>
            </td>
            <td>
              フォロワー数：<%= user.followers.count%>
            </td>
            <%if current_user == user%>
              <td>
              </td>
            <% else %>
              <% if current_user.following?(user) %>
                <td>
                  <%= link_to "フォローを外す", user_relationships_path(user.id) , method: :delete%>
                </td>
              <% else %>
                <td>
                  <%= link_to "フォローする", user_relationships_path(user.id) , method: :post%>
                </td>
              <% end %>
            <% end %>
            <td>
              <%= link_to "Show" , user_path(user.id) ,class:"user_16454" %>
            </td>
          </tr>
        <% end %>
        </tbody>
        </table>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/new' , user: @user %>
      <%= render 'users/follow_form', user: @user %>
      <%= render 'books/form' ,book:@book%>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr> 
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
                <%= attachment_image_tag book.user, :profile_image ,class:"attachment user profile_image fallback" ,format: 'jpeg', fallback:"no_image.jpg",size: "40x40"%>
            </td>
            <td>
              <%= link_to book_path(book.id) do %>
              <%= book.title %>
              <% end %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>