config/routes.rb
Rails.application.routes.draw do
  root "users#home"
  get "home/about" => "users#about"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships,  only: [:create, :destroy]
  end
  get "searches" => "searches#index"
  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  validates :title , presence: true
  validates :body , presence: true
  validates :body ,length: { maximum:200 }
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  class << self
    def search(search,word)
      if search == "forward_match"
        @books = Book.where("title LIKE?","#{word}%")
      elsif search == "backward_match"
        @books = Book.where("title LIKE?","%#{word}")
      elsif search == "perfect_match"
        @books = Book.where(title: word)
      elsif search == "partial_match"
        @books = Book.where("title LIKE?","%#{word}%")
      else
        @books = Book.all
      end
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have creatad book successfully."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user.id)
      @books = Book.all
      render :index
    end
  end
  def index
    @books = Book.all
    @user = User.find(current_user.id)
    @book = Book.new
  end
  def show
    @user = User.find(current_user.id)
    @user_book = Book.find(params[:id])
    @book = Book.new
    @user_book_comments = @user_book.book_comments
    @book_comment = BookComment.new
  end
  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path
  end

  private
  def book_params
    params.require(:book).permit(:title,:body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment_form.html.erb
<%= form_with(model: [user_book,book_comment] ) do |f| %>
  <%= f.text_area :comment , rows:"5",class: "form-control"%>
  <%= f.submit "送信"%>
<% end %>

app/views/books/_comments_index.html.erb
<% user_book_comments.each do |book_comment| %>
  <div class="comment">
    <%= attachment_image_tag book_comment.user, :profile_image ,class:"attachment user profile_image fallback" ,format: 'jpeg', fallback:"no_image.jpg",size: "40x40" %>
    <%= book_comment.comment %>
    <% if book_comment.user == current_user %>
      <%= link_to "Delete", book_book_comment_path(book_comment.book, book_comment) , method: :delete , class:"btn-sm btn-danger destroy_book_26656", remote: true %>
    <% end %>
    <br>
    <%= book_comment.user.name %>
  </div>
  <% end %>

app/views/books/_favorite.html.erb
                <% if book.favorited_by?(current_user) %>
                  <li>
                    <%= link_to book_favorites_path(book), method: :delete,remote: true do %>
                      <i class="fa fa-heart" aria-hidden="true" style="color: red;" ></i>
                      <%= book.favorites.count%>
                    <% end %>
                  </li>
                <% else %>
                <li>
                  <%= link_to book_favorites_path(book), method: :post, remote: true do %>
                    <i class="fa fa-heart-o" aria-hidden="true"  ></i>
                    <%= book.favorites.count %>
                  <% end %>
                </li>
                <% end %>

app/views/books/_form.html.erb
<h2>New book</h2>
<%= form_for(book, url: books_path) do |f| %>
  <div class="field row">
    <%= f.label :title %>
    <%= f.text_field :title, autoforcus: true,class:"col-xs-12 book_title" %>
  </div>
  <div class="field row">
    <%= f.label :body, "Opinion" %>
    <%= f.text_area :body, class:"col-xs-12 book_body" %>
  </div>

  <div class="actions row">
    <%= f.submit "Create Book", class:"btn btn-primary col-xs-12" %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="body">
  <div class="container">

  <div class="row">
	  <div class="col-md-6 col-md-offset-3">
		  <h1>Editing Book</h1>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

      <%= form_for(@book, url: book_path) do |f| %>
      
      <div class="field row">
        <%= f.label :title %>
        <%= f.text_field :title , class:"col-xs-12 book_title" %>
      </div>

      <div class="field row">
        <%= f.label :body , "Opinion" %>
        <%= f.text_area :body , class:"col-xs-12 book_body" %>
      </div>

      <div class="actions row">
        <%= f.submit "Update Book", class:"btn btn-primary col-xs-12"%>
      </div>

      <% end %>
    <%= link_to "Show" , book_path(@book.id) %> |
    <%= link_to "Back" , books_path %>
    </div>
    <div class="col-md-3"></div>
  </div>
  </div>
</div>

app/views/books/index.html.erb
<body>
  <div class="container">
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
        <ul>
          <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">

    <div class="col-xs-3">
      <%= render 'users/new' , user: @user %>
      <%= render 'users/edit'%>
      <%= render 'books/form' ,book:@book%>
    </div>
    <div class="col-xs-9">
      <h2>Books</h2>

      <table class="table table-hover table-inverse">
        <thead>
          <tr> 
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image ,class:"attachment user profile_image fallback" ,format: 'jpeg', fallback:"no_image.jpg",size: "40x40" %>
                <% end %>
              </td>
              <td>
                <%= link_to book_path(book.id) do %>
                  <%= book.title %>
                <% end %>
              </td>
              <td>
                <%= book.body %>
              </td>
              <td>
                <div class="favorites_buttons_<%= book.id %>">
                  <%= render "books/favorite" , book:book%>
                </div>
              </td>
              <td>
                <%=  "コメント数：#{book.book_comments.count}"  %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      </div>
    </div>
  </div>
</body>

app/views/books/index.js.erb
$("#comments_area").html("<%= j(render 'books/comments_index', user_book: @user_book ) %>");
$("textarea").val('');

app/views/books/show.html.erb
<body>
<div class="container">
      <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
  <div class="row">
    <div class="col-xs-3">
      <%= render 'users/new' , user: @user %>
      <%= render 'users/edit'%>
      <%= render 'books/form' ,book:@book%>
    </div>

  <div class="col-xs-9">
		<h2>Book detail</h2>
		<table class="table">
		  <tbody>
        <tr>
          <td>
            <%= link_to user_path(@user_book.user_id) do %>
              <%= attachment_image_tag @user_book.user, :profile_image ,class:"attachment user profile_image fallback" ,format: 'jpeg', fallback:"no_image.jpg",size: "40x40" %>
              <br>
              <%= @user_book.user.name %>
            <% end %>
          </td>
          <td>
            <%= link_to book_path(@user_book.id) do %>
            <%= @user_book.title %>
            <% end %>
          </td>
          <td>
            <%= @user_book.body %>
          </td>
          <% if @user_book.user_id == @user.id %>
          <td>
              <%= link_to "Edit" , edit_book_path(@user_book.id) , class:"btn-sm btn-success edit_book_26656" %>
          </td>
          <% end %>
          <% if @user_book.user_id == @user.id %>
          <td>
              <%= link_to "Destroy", book_path(@user_book.id) ,method: :delete, class:"btn-sm btn-danger destroy_book_26656", data: { confirm: "本当に消しますか？" }  %>
          </td>
          <% end %>
          <td>
            <% if @user_book.favorited_by?(current_user) %>
              <li>
                <%= link_to book_favorites_path(@user_book), method: :delete do %>
                  <i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
                  <%= @user_book.favorites.count%>
                <% end %>
              </li>
            <% else %>
              <li>
                <%= link_to book_favorites_path(@user_book), method: :post do %>
                  <i class="fa fa-heart-o" aria-hidden="true"></i>
                  <%= @user_book.favorites.count %>
                <% end %>
              </li>
            <% end %>
          </td>
          <td>
            コメント数：<%= @user_book.book_comments.count %>
          </td>
        </tr>  
      </tbody>
    </table>
    <div id="comments_area">
      <%= render 'books/comments_index', user_book_comments:@user_book_comments %>
    </div>
      <%= render 'books/comment_form', {user_book: @user_book, book_comment:@book_comment} %>
  </div>
</div>
</body>