config/routes.rb
Rails.application.routes.draw do
  root "users#home"
  get "home/about" => "users#about"
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show,:index, :edit, :update] do
    resource :relationships,  only: [:create, :destroy]
  end
  get "searches" => "searches#index"
  resources :books, only: [:create,:index,:show,:edit,:update,:destroy] do
    resources :book_comments, only: [:create, :destroy]
    resource :favorites, only: [:create, :destroy]
  end
  resources :users do
    member do
      get :following, :followers
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookersNext</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="navbar navbar-fixed-top navbar-inverse learfix">
  <div class="container clearfix">
    <nav class="nav navbar-nav navbar-left clearfix">
      <span>Bookers</span>
    </nav>
    <nav>
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right clearfix">
        <li><%= link_to " Home", user_path(current_user.id),class:"glyphicon glyphicon-home home" %></li>
        <li><%= link_to " Users", users_path ,class:"glyphicon glyphicon-user users" %></li>
        <li><%= link_to " Books", books_path , class:"glyphicon glyphicon-book books" %></li>
        <li><%= link_to " logout", destroy_user_session_path , method: :delete , class:"glyphicon glyphicon-log-out logout"%></li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right clearfix">
        <li><%= link_to " Home", root_path , class:"glyphicon glyphicon-home home" %></li>
        <li><%= link_to " About", home_about_path, class:"glyphicon glyphicon-link about" %></li>
        <li><%= link_to " sign up", new_user_registration_path , class:"glyphicon glyphicon-edit sign_up" %></li>
        <li><%= link_to " login", new_user_session_path , class:"glyphicon glyphicon-log-in sign_in" %></li>
      </ul>
    <% end %>
    </nav>
  </div>
  </header>
    <%if user_signed_in? %>
      <div class="row">
        <div class="col-xs-7 col-xs-offset-5">
          <%= form_tag :searches,method: :get, class:"search" do %>
            <%= text_field_tag (:word) %>
            <%= select_tag 'range' ,options_for_select([ ['User', '1'], ['Book', '2']]) %>
            <%= select_tag 'search', options_for_select([["前方一致","forward_match"], ["後方一致","backward_match"], ["完全一致","perfect_match"], ["部分一致","partial_match"]]) %>
            <%= submit_tag "検索"%>
          <% end %>
        </div>
      </div>
    <% end %>
  <%= yield %>
    <footer>
    <div class="container">
  	  <div class="row">
    	  <div class="col-xs-3 col-xs-offset-9">
    		  <p>CopyRight Infratop.inc</p>
    	  </div>
      </div>
    </div>
    </footer>
  </body>
</html>